### REST Client extension
@hostname = http://localhost:8080
###
GET {{hostname}}/comedians

###
GET {{hostname}}/comedians/1

###
GET {{hostname}}/comedians/111

###
GET {{hostname}}/users

###
GET {{hostname}}/clients/1

###
POST {{hostname}}/clients

{
  "fullName": "Max",
  "phone": "12345678901",
  "ticketNumber": "1",
  "booking": [{"comedian": 5, "time": "20:00"}]
}

###
PATCH {{hostname}}/clients/1

{
  "fullName": "MaxMaxMax",
  "phone": "12345678901",
  "ticketNumber": "1",
  "booking": [{"comedian": 5, "time": "20:00"}]
}
